version: '3.8'

x-defaults:
  &defaults
  init: true
  tty: true
  networks:
    - relearn_network

networks:
  relearn_network:

services:
    api:
        <<: *defaults
        ports:
          - "3010:3010"
        command: yarn workspace @relearn/api start:prod
        environment:
          - PORT=3010
        build:
          # args:
          #   APP: "@relearn/api"
          #   START_COMMAND: start:prod
          context: .
          dockerfile: ./apps/api/Dockerfile
        volumes:
          - ./apps/api:/app/apps/api
          - /app/apps/api/node_modules
    identity:
        <<: *defaults
        ports:
          - "3009:3009"
        command: yarn workspace @relearn/identity start:prod
        environment:
          - PORT=3009
        build:
          # args:
          #   APP: "@relearn/api"
          #   START_COMMAND: start:prod
          context: .
          dockerfile: ./apps/identity/Dockerfile
        volumes:
          - ./apps/identity:/app/apps/identity
          - /app/apps/identity/node_modules